### ISSUE TITLE
Warn IE users to: DON'T

### ISSUE THREAD

**Issue by rhodges** [Ecotrust/forestplanner#351]
"Forest Planner is not supported on Internet Explorer. Please use one of the following: FireFox, Safari, or Google Chrome."

Ideally we'd want to lock them out of trying to use IE entirely, but a basic javascript "alert" will go a long way to reducing the alienation of our users.

**Comment by rhodges** [comment]
This might be fixed, but testing on David's IE v11 gives an unclear picture:
1 - the alert doesn't show, in fact the test for IE version returns a -1 value and on inspection claims to be Netscape, not IE (wtf!?)
2 - v10 and older seem to display the correct warning. 
3 - v11 (claiming to be Netscape) loads the page fine, so really doesn't need the warning.
4 - David trying v10 does not give the warning, but seems locked down by security - I think he disabled the warning that the site (and almost all sites) are locked down and disallowed.

**Comment by willthemoor** [comment]
Ryan, you might try ditching the JS and adding something like this to the HTML:

```html
<!-- add this just after the <body> opening-->
<!--[if IE]>
<p class="chromeframe">
        Thanks for using Forest Planner! Unfortunately, 
        <strong>Internet Explorer is not supported</strong> at this time.
        Please, try a <a href="http://browsehappy.com/">different browser</a>
        or <a href="http://www.google.com/chromeframe/?redirect=true">
        activate Google Chrome Frame</a> to use Forest Planner.
    </p>
<![endif]-->
```

To be difficult, IE10 and beyond have [dropped support for conditional comments](https://msdn.microsoft.com/en-us/library/ie/hh801214%28v=vs.85%29.aspx). Rich. Adding this meta tag to the `<head>` is supposed to work. This ticket may not be the place to discuss it but what's the problem in IE10+ anyway?

```html
  <meta http-equiv="X-UA-Compatible" content="IE=EmulateIE9">
```

This CSS seemed to work OK via dev tools:

```css
.chromeframe {
    background-color: #ffffff;
    border: 13px solid #ff0000;
    font-size: 24px;
    line-height: 1.25;
    margin: 40px auto 80px;
    width: 700px;
    padding: 20px;
}
.chromeframe > strong {
    background-color: #888888;
    color: #ffffff;
    display: inline-block;
    font-weight: normal;
    padding: 0 3px;
}


/* just hide the nav bar to avoid confusion */
.chromeframe + .navbar-fixed-top {
    display: none;
}
```
